# Generated by Django 3.2.6 on 2021-10-14 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
