# Generated by Django 3.2.6 on 2021-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0003_orden_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='valor',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
    ]
