# Generated by Django 2.2 on 2021-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0005_orden_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
