# Generated by Django 2.2 on 2021-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0007_remove_orden_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='token',
            field=models.CharField(default='', max_length=60),
        ),
    ]
