# Generated by Django 3.2.6 on 2021-10-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orden', '0002_orden_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1000)),
                ('orden', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Orden.orden')),
            ],
        ),
    ]
