# Generated by Django 3.2.6 on 2021-10-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_orden_estado'),
        ('SAP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sap',
            name='id',
        ),
        migrations.AlterField(
            model_name='sap',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Orden.orden'),
        ),
    ]
